### ISSUE TITLE
failed to test aiohttp session

### ISSUE THREAD

**Issue by vanyakosmos** [pytest-dev/pytest-asyncio#139] opened 2020-02-09 17:15 UTC
minimal example:
```
import aiohttp
import pytest

@pytest.mark.asyncio
async def test_http():
    async with aiohttp.ClientSession() as s:
        assert await s.get('https://python.org')
```

error logs 
```
Test session starts (platform: darwin, Python 3.8.0, pytest 5.3.5, pytest-sugar 0.9.2)
cachedir: .pytest_cache
rootdir: /Users/Vania/projects/traktogram, inifile: pytest.ini
plugins: sugar-0.9.2, asyncio-0.10.0, cov-2.8.1
collecting ...


―――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR at teardown of test_http ――――――――――――――――――――――――――――――――――――――――――――――――――――――――

request = <SubRequest 'event_loop' for <Function test_http>>

    @pytest.yield_fixture
    def event_loop(request):
        """Create an instance of the default event loop for each test case."""
        loop = asyncio.get_event_loop_policy().new_event_loop()
        yield loop
>       loop.close()

../../.pyenv/versions/3.8.0/envs/teletrakt/lib/python3.8/site-packages/pytest_asyncio/plugin.py:209:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
uvloop/loop.pyx:1366: in uvloop.loop.Loop.close
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   OSError: [Errno 16] Resource busy

uvloop/loop.pyx:583: OSError
----------------------------------------------------------- Captured stderr teardown -----------------------------------------------------------
Traceback (most recent call last):
  File "uvloop/handles/handle.pyx", line 96, in uvloop.loop.UVHandle._warn_unclosed
ResourceWarning: unclosed resource <TCPTransport closed=False reading=True 0x7fdd7067bf60>
Exception ignored in: 'uvloop.loop.__uv_walk_close_all_handles_cb'
Traceback (most recent call last):
  File "uvloop/handles/handle.pyx", line 96, in uvloop.loop.UVHandle._warn_unclosed
ResourceWarning: unclosed resource <TCPTransport closed=False reading=True 0x7fdd7067bf60>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 979, in uvloop.loop.__uv_stream_buffered_on_read
  File "uvloop/sslproto.pyx", line 385, in uvloop.loop.SSLProtocol.buffer_updated
  File "uvloop/sslproto.pyx", line 579, in uvloop.loop.SSLProtocol._do_shutdown
  File "uvloop/sslproto.pyx", line 589, in uvloop.loop.SSLProtocol._on_shutdown_complete
  File "uvloop/loop.pyx", line 1259, in uvloop.loop.Loop.call_soon
  File "uvloop/loop.pyx", line 635, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 639, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 668, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/handles/basetransport.pyx", line 41, in uvloop.loop.UVBaseTransport._fatal_error
  File "uvloop/handles/basetransport.pyx", line 236, in uvloop.loop.UVBaseTransport._force_close
  File "uvloop/handles/basetransport.pyx", line 32, in uvloop.loop.UVBaseTransport._schedule_call_connection_lost
  File "uvloop/loop.pyx", line 639, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 668, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
Exception ignored in: 'uvloop.loop.__uv_stream_buffered_on_read'
Traceback (most recent call last):
  File "uvloop/handles/basetransport.pyx", line 41, in uvloop.loop.UVBaseTransport._fatal_error
  File "uvloop/handles/basetransport.pyx", line 236, in uvloop.loop.UVBaseTransport._force_close
  File "uvloop/handles/basetransport.pyx", line 32, in uvloop.loop.UVBaseTransport._schedule_call_connection_lost
  File "uvloop/loop.pyx", line 639, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 668, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
                                                                                                                                 100% ██████████

Results (0.88s):
       1 passed
       1 error
```

Also tested with python3.7. Same error.

**Comment by simonfagerholm** [comment] 2020-04-25 09:29
@vanyakosmos  I'm unsuccessful in reproducing this on my side, however I'm running on windows and use python 3.7.7.
Can you provide a complete list of installed packages?
Also are you running your example in a completely separate environment, so that you don't get any influence for example from a `conftest.py` in your traktogram project?

**Comment by Tinche** [comment] 2020-04-25 18:00
The fact that the stack trace mentions uvloop means there's more going on here on the OP's side.

**Comment by seifertm** [comment] 2022-01-16 09:37
@vanyakosmos I was also unable to reproduce your issue with pytest-asyncio 0.17.0 and uvloop installed. I'm closing this issue for now.

Please try and upgrade to a recent pytest-asyncio version and retest. If you're still experiencing problems, feel free to reopen this issue.

**Closed by seifertm** 2022-01-16 09:37 UTC
