### ISSUE TITLE
RuntimeError: "Timeout context manager should be used inside a task" in aiohttp with version 0.23 pytest-asyncio

### ISSUE THREAD

**Issue by UrbanKeith** [pytest-dev/pytest-asyncio#762] opened 2024-01-24 10:55 UTC
I'm using a fixture to send HTTP requests through a closure function with _aiohttp_ like this:
```python

@pytest_asyncio.fixture(scope="session")
async def session() -> AsyncGenerator:
    session = aiohttp.ClientSession()
    yield session
    await session.close()

@pytest_asyncio.fixture(scope="session")
async def make_request(session: aiohttp.ClientSession) -> Callable:
    async def inner(
        url: str,
        params: dict | None = None,
        body: dict | bytes | None = None,
        headers: dict | None = None,
        http_method: Literal["get", "post", "patch", "put"] = "get",
    ) -> HTTPResponse:
        params = params or {}
        headers = headers or {}
        full_url = f"{settings.url}/app/gantt/api/{url}"
        async with getattr(session, http_method)(full_url, params=params, json=body, headers=headers) as response:
            return HTTPResponse(
                body=await response.json() or await response.reason(),
                headers=response.headers,
                status=response.status,
            )

    return inner
    
@pytest.mark.asyncio()
async def test_some(make_request):
    response = await make_request(
        url="some_url",
        http_method="get",
    )    
```

python==3.11.7
aiohttp==3.9.1
pytest==7.4.4

If I use the old version of the pytest-asyncio library (pytest-asyncio==0.21.1), then everything works as it should.
But if I use the new version of the library (pytest-asyncio==0.23.3), I get this error:

```
============================== 1 failed in 0.20s ===============================
FAILED                                        [100%]
src/tests/functional/project/test_project.py:25 (test_some)
make_request = <function make_request.<locals>.inner at 0x7f23cc4ad260>

    @pytest.mark.asyncio()
    async def test_some(make_request):
>       response = await make_request(
            url="some_url",
            http_method="get",
        )

test_project.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../conftest.py:139: in inner
    async with getattr(session, http_method)(full_url, params=params, json=body, headers=headers) as response:
/home/myuser/.cache/pypoetry/virtualenvs/myvenv-ESl80ZOh-py3.11/lib/python3.11/site-packages/aiohttp/client.py:1187: in __aenter__
    self._resp = await self._coro
/home/myuser/cache/pypoetry/virtualenvs/myvenv-back-ESl80ZOh-py3.11/lib/python3.11/site-packages/aiohttp/client.py:500: in _request
    with timer:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiohttp.helpers.TimerContext object at 0x7f23ccf23850>

    def __enter__(self) -> BaseTimerContext:
        task = current_task(loop=self._loop)
    
        if task is None:
>           raise RuntimeError(
                "Timeout context manager should be used " "inside a task"
            )
E           RuntimeError: Timeout context manager should be used inside a task

/home/myuser/.cache/pypoetry/virtualenvs/myvenv-back-ESl80ZOh-py3.11/lib/python3.11/site-packages/aiohttp/helpers.py:715: RuntimeError
```

I dug into the code for a long time, but could not understand what exactly this was connected with. Somehow the closing function loses connection with the event loop or something like that.
Tell me what's the matter? Is this a bug or am I doing something wrong?

**Comment by seifertm** [comment] 2024-01-28 19:55
I assume this is a duplicate of #706 .

Starting with v0.23 pytest-asyncio has the possibility to run tests and fixtures in different event loops. Essentially, there's one event loop for each hierarchy level of the test suite (function, class, module, package, session).

However, pytest-asyncio wrongly assumes that the scope of the fixture is also the scope of the event loop that should be used. This makes it impossible to have a session-scoped fixture that runs in the same event loop as function-scoped tests, for example.

We need to find a way to separate fixture scope from event loop scope, to make everyone happy.

I assume this is the underlying issue in your example. I'll close this as a duplicate of #706.

**Closed by seifertm** 2024-01-28 19:55 UTC
