### ISSUE TITLE
python-asyncio

### ISSUE THREAD

**Issue by verfired8975** [pytest-dev/pytest-asyncio#327] opened 2022-04-11 08:58 UTC
pls help mq 
```
\server.py", line 679, in <module>
    main()
  File server.py", line 675, in main
    asyncio.get_event_loop().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
```

Commands
    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()

i am running server.py but this error

**Comment by seifertm** [comment] 2022-04-11 11:01
@verfired8975 I'm sorry, but I cannot follow.

You opened an issue for pytest-asyncio. I see that you are using asyncio, but I fail to see how your problem is related to the pytest plugin for asyncio.

I also don't understand the problem you are experiencing. Can you explain what's happening and provide a minimal reproducible example?

**Comment by seifertm** [comment] 2022-04-22 13:58
I'm closing this issue, since no additional information was provided.

**Closed by seifertm** 2022-04-22 13:58 UTC
