### ISSUE TITLE
v0.12.0 is incompatible with pytest-socket + mocked aiohttp request (aioresponses)

### ISSUE THREAD

**Issue by gaffney** [pytest-dev/pytest-asyncio#160] opened 2020-05-13 02:56 UTC
I immediately receive this error on any test marked with `@pytest.mark.asyncio` that mocks out the `aiohttp` calls after upgrading to 0.12.0. Downgrading to 0.11.0 resolves the issue.

**conftest.py**
```python
def pytest_runtest_setup():
    pytest_socket.disable_socket()
```

Using [aioresponses](https://github.com/pnuckowski/aioresponses) to mock out the `asyncio` bit:

```python
# -*- coding: utf-8 -*-

import aioresponses

@pytest.fixture()
def mocked_aioresponses():
    with aioresponses.aioresponses() as rsps:
        yield rsps
```

Test looks something like:

```python
@pytest.mark.asyncio
async def test_function_that_makes_an_async_external_api_call(mocked_aioresponses):
    mocked_aioresponses.get(
        "https://example.com/api/",
        status=200,
        payload={"api": "result"},
    )
    result = await function_that_makes_an_async_external_api_call()
    assert result == {"api": "result"}
```

Where `function_that_makes_an_async_external_api_call` would be something along the lines of:

```python
async def function_that_makes_an_async_external_api_call():
    async with aiohttp.ClientSession() as session:
        async with session.get("https://example.com/api/") as response:
            api_result = await response.json()
            if response.status != 200:
                raise ExampleAPIError()
            return api_result
```

**Stack trace**:
```
../../../.local/share/virtualenvs/proj-XeKm4Czd/lib/python3.7/site-packages/pytest_asyncio/plugin.py:56:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../.local/share/virtualenvs/proj-XeKm4Czd/lib/python3.7/site-packages/pytest_asyncio/plugin.py:184: in event_loop
    loop = asyncio.get_event_loop_policy().new_event_loop()
../../../.pyenv/versions/3.7.5/lib/python3.7/asyncio/events.py:660: in new_event_loop
    return self._loop_factory()
../../../.pyenv/versions/3.7.5/lib/python3.7/asyncio/unix_events.py:51: in __init__
    super().__init__(selector)
../../../.pyenv/versions/3.7.5/lib/python3.7/asyncio/selector_events.py:55: in __init__
    self._make_self_pipe()
../../../.pyenv/versions/3.7.5/lib/python3.7/asyncio/selector_events.py:102: in _make_self_pipe
    self._ssock, self._csock = socket.socketpair()
../../../.pyenv/versions/3.7.5/lib/python3.7/socket.py:492: in socketpair
    a = socket(family, type, proto, a.detach())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<AddressFamily.AF_UNIX: 1>, <SocketKind.SOCK_STREAM: 1>, 0, 13), kwargs = {}

    def guarded(*args, **kwargs):
>       raise SocketBlockedError()
E       pytest_socket.SocketBlockedError: A test tried to use socket.socket.

../../../.local/share/virtualenvs/proj-XeKm4Czd/lib/python3.7/site-packages/pytest_socket.py:71: SocketBlockedError
```

**Comment by simonfagerholm** [comment] 2020-05-13 05:56
I tried the following test with `pytest-socket` and the conftest that you provided. Both fail with the error you get. Also tried `pytest-asyncio==0.11` and that also fails.

As this happens for both synchronous and asynchronous use of `socket`, this seems unrelated to `pytest-asyncio`. 

Also the error seems the be the main feature of pytest-socket, and expected behaviour when using a socket:

> Run pytest --disable-socket, tests should fail on any access to socket or libraries using socket with a SocketBlockedError.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import asyncio
import socket

import pytest


def test_socket_sync():
    con = socket.create_connection(('127.0.0.1', 80))
    assert con


@pytest.mark.asyncio
async def test_socket_async():
    reader, writer = await asyncio.open_connection('127.0.0.1', 80)
    assert reader
    assert writer

```

**Comment by simonfagerholm** [comment] 2020-05-13 06:22
I tried the following test with `pytest-socket` and the conftest that you provided. Both fail with the error you get. Also tried `pytest-asyncio==0.11` and that also fails.

As this happens for both synchronous and asynchronous use of `socket`, this seems unrelated to `pytest-asyncio`. However I might be totally misunderstanding you, as you didn't provide an example of how you use` pytest-socket`.

I'm not familiar with` pytest-socket` but the error seems the be the main feature of `pytest-socket`, and expected behaviour when using a socket:

> Run pytest --disable-socket, tests should fail on any access to socket or libraries using socket with a SocketBlockedError.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import asyncio
import socket

import pytest


def test_socket_sync():
    con = socket.create_connection(('127.0.0.1', 80))
    assert con


@pytest.mark.asyncio
async def test_socket_async():
    reader, writer = await asyncio.open_connection('127.0.0.1', 80)
    assert reader
    assert writer

```

**Comment by gaffney** [comment] 2020-05-14 03:01
Ahh my bad, I did not realize there was some other fancy sauce going on. Looking at the actual test now, it uses a fixture that uses [aioresponses](https://github.com/pnuckowski/aioresponses) to mock out the `asyncio` bit.

```python
# -*- coding: utf-8 -*-

import aioresponses

@pytest.fixture()
def mocked_aioresponses():
    with aioresponses.aioresponses() as rsps:
        yield rsps
```

Then in the test it does something like:

```python
@pytest.mark.asyncio
async def test_function_that_makes_an_async_external_api_call(mocked_aioresponses):
    mocked_aioresponses.get(
        "https://example.com/api/",
        status=200,
        payload={"api": "result"},
    )
    function_that_makes_an_async_external_api_call()
```

Where `function_that_makes_an_async_external_api_call` is something along the lines of

```python
async def function_that_makes_an_async_external_api_call():
    async with aiohttp.ClientSession() as session:
        async with session.get("https://example.com/api/") as response:
            api_result = await response.json()
            if response.status != 200:
                raise ExampleAPIError()
            return api_result
```

Apologies for not spending a little more time to ensure I was not making a crappy bug report.

**Comment by simonfagerholm** [comment] 2020-05-14 07:39
Hi! Thanks for the update and clarifications, now I understand it more clearly.
I still can't replicate it working with `pytest-asyncio 0.11`, even with different combinations of `pytest-socket` versions, but I did some digging in the code anyway.

Unfortunately this does not seem to be a problem with `pytest-asyncio`, but a general incompatibility between `pytest-socket` and `asyncio`.
There are currently two open issues regarding this:
https://github.com/miketheman/pytest-socket/issues/7 that in turn is marked as a duplicate of https://github.com/miketheman/pytest-socket/issues/6.

The problem seems to stem from the fact that the event loops in `asyncio` rely on sockets for syncing (or so it seems, from a quick look into the asyncio code).

How it has ever worked for you, I cannot explain. But the problem seems to have existed since 2018 in `pytest-socket`.

**Comment by simonfagerholm** [comment] 2020-05-14 07:51
A solution would be to not disable `sockets`, but disable `sockets.connect` by using 'socket_allow_hosts':

**conftest.py**
```python
pytest_plugins = ['asyncio', 'socket']
```
**test_socket.py**
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import aiohttp
import aioresponses
import pytest


async def function_that_makes_an_async_external_api_call():
    async with aiohttp.ClientSession() as session:
        async with session.get('https://google.se') as response:
            api_result = await response.text()
            if response.status != 200:
                raise RuntimeError()
            return api_result


@pytest.fixture()
def mocked_aioresponses():
    with aioresponses.aioresponses() as rsps:
        yield rsps


@pytest.mark.allow_hosts(['127.0.0.1', '::1'])
@pytest.mark.asyncio
async def test_without_mock():
    result = await function_that_makes_an_async_external_api_call()
    assert result == 'test'


@pytest.mark.allow_hosts(['127.0.0.1', '::1'])
@pytest.mark.asyncio
async def test_with_mock(
        mocked_aioresponses
    ):
    mocked_aioresponses.get(
        'https://google.se',
        status=200,
        body='test',
    )
    result = await function_that_makes_an_async_external_api_call()
    assert result == 'test'
```

```
Testing started at 09:43 ...
python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py" --path test_socket.py
Launching pytest with arguments test_socket.py in abc

============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- python.exe
cachedir: .pytest_cache
rootdir: abc
plugins: asyncio-0.12.0, socket-0.3.3
collecting ... collected 2 items

test_async_prob.py::test_without_mock FAILED                             [ 50%]
test_async_prob.py:22 (test_without_mock)
@pytest.mark.allow_hosts(['127.0.0.1', '::1'])
    @pytest.mark.asyncio
    async def test_without_mock():
>       result = await function_that_makes_an_async_external_api_call()

test_socket.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_socket.py:10: in function_that_makes_an_async_external_api_call
    async with session.get('https://google.se') as response:
venv\lib\site-packages\aiohttp\client.py:1012: in __aenter__
    self._resp = await self._coro
venv\lib\site-packages\aiohttp\client.py:483: in _request
    timeout=real_timeout
venv\lib\site-packages\aiohttp\connector.py:523: in connect
    proto = await self._create_connection(req, traces, timeout)
venv\lib\site-packages\aiohttp\connector.py:859: in _create_connection
    req, traces, timeout)
venv\lib\site-packages\aiohttp\connector.py:986: in _create_direct_connection
    req=req, client_error=client_error)
venv\lib\site-packages\aiohttp\connector.py:936: in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
..\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py:941: in create_connection
    await self.sock_connect(sock, address)
..\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py:464: in sock_connect
    return await fut
..\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py:469: in _sock_connect
    sock.connect(address)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

inst = <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
args = (('172.217.17.67', 443),), host = '172.217.17.67'

    def guarded_connect(inst, *args):
        host = host_from_connect_args(args)
        if host and host in allowed:
            return _true_connect(inst, *args)
>       raise SocketConnectBlockedError(allowed, host)
E       pytest_socket.SocketConnectBlockedError: A test tried to use socket.socket.connect() with host "172.217.17.67" (allowed: "127.0.0.1,::1").

venv\lib\site-packages\pytest_socket.py:139: SocketConnectBlockedError

test_async_prob.py::test_with_mock PASSED                                [100%]

================================== FAILURES ===================================
______________________________ test_without_mock ______________________________

    @pytest.mark.allow_hosts(['127.0.0.1', '::1'])
    @pytest.mark.asyncio
    async def test_without_mock():
>       result = await function_that_makes_an_async_external_api_call()

test_async_prob.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_async_prob.py:10: in function_that_makes_an_async_external_api_call
    async with session.get('https://google.se') as response:
venv\lib\site-packages\aiohttp\client.py:1012: in __aenter__
    self._resp = await self._coro
venv\lib\site-packages\aiohttp\client.py:483: in _request
    timeout=real_timeout
venv\lib\site-packages\aiohttp\connector.py:523: in connect
    proto = await self._create_connection(req, traces, timeout)
venv\lib\site-packages\aiohttp\connector.py:859: in _create_connection
    req, traces, timeout)
venv\lib\site-packages\aiohttp\connector.py:986: in _create_direct_connection
    req=req, client_error=client_error)
venv\lib\site-packages\aiohttp\connector.py:936: in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
..\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py:941: in create_connection
    await self.sock_connect(sock, address)
..\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py:464: in sock_connect
    return await fut
..\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py:469: in _sock_connect
    sock.connect(address)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

inst = <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
args = (('172.217.17.67', 443),), host = '172.217.17.67'

    def guarded_connect(inst, *args):
        host = host_from_connect_args(args)
        if host and host in allowed:
            return _true_connect(inst, *args)
>       raise SocketConnectBlockedError(allowed, host)
E       pytest_socket.SocketConnectBlockedError: A test tried to use socket.socket.connect() with host "172.217.17.67" (allowed: "127.0.0.1,::1").

venv\lib\site-packages\pytest_socket.py:139: SocketConnectBlockedError
=========================== short test summary info ===========================
FAILED test_socket.py::test_without_mock - pytest_socket.SocketConnectBlo...
========================= 1 failed, 1 passed in 0.59s =========================

Process finished with exit code 1

Assertion failed

Assertion failed

Assertion failed

Assertion failed

```

**Comment by simonfagerholm** [comment] 2020-05-15 18:17
@gaffney Did that solve it for you?

**Comment by gaffney** [comment] 2020-05-16 04:25
Hey @simonfagerholm thanks for your response, and yes that works. I actually added that to every test to avoid adding the marker everywhere manually.

```python
def pytest_collection_modifyitems(config, items):
    # block all external socket connections by default
    for item in items:
        item.add_marker(pytest.mark.allow_hosts(['127.0.0.1', '::1']))
```

Thanks!

**Closed** 2020-05-18 03:02 UTC

**Comment by john-kurkowski** [comment] 2024-08-21 22:34
I came here from Google. While the above solution works, pytest-socket now has a simpler solution as of miketheman/pytest-socket#54: run Pytest with the additional `--allow-unix-socket` flag, e.g. `pytest --disable-socket --allow-unix-socket`.
