### ISSUE TITLE
can i get a hold of the event_loop in setup_module?

### ISSUE THREAD

**Issue by tony-kerz** [pytest-dev/pytest-asyncio#79] opened 2018-03-05 16:43 UTC
trying to initialize something once for the entire module:
```
AsyncIOMotorClient(url, io_loop=event_loop)
```

**Comment by asvetlov** [comment] 2018-03-05 17:24
You cannot, `event_loop` is a *test function* scoped fixture.

**Comment by tony-kerz** [comment] 2018-03-05 18:27
gotcha, thanks andrew.

any idea if there is a way to inject the event loop that pytest-asyncio will use?

**Comment by asvetlov** [comment] 2018-03-05 19:01
Overriding *functional scoped* `event_loop` fixture with custom one in `conftest.py` with `scope='module'` can help but I really very discourage this solution.

The problem is: if a loop is created *per test* all your tests are **isolated**. After a test run loop can have not finished tasks, open sockets and other scheduled events. These events may raise an exception inside the next test. Debugging the error becomes a nightmare very easy.

Much better way is instead `setup_module()` to use a fixture for motor client like:
```
@pytest.fixture
def motor(event_loop):
    ret = AsyncIOMotorClient(URLl, io_loop=event_loop)
    yield ret
    ret.close()
```

And after this just add `motor` parameter to every test which need the client.

**Comment by tony-kerz** [comment] 2018-03-05 20:03
wow, that async fixture trick works nicely for passing along a `motor` reference to tests.

i still have an issue in that i wanted to do some function setup/teardown using motor to initialize the database before each test function.

i may just use the non-motor py-mongo client to accomplish that, but wondering if you had any idea how to get the `motor` fixture reference to `teardown_function`...?

**Comment by simonfagerholm** [comment] 2020-04-30 09:07
@tony-kerz This seems to be a non-issue, would you mind closing it?

**Closed** 2022-01-08 13:01 UTC
