### ISSUE TITLE
Async fixtures appear to be broken with pytest==3.7

### ISSUE THREAD

**Issue by orf** [pytest-dev/pytest-asyncio#90] opened 2018-08-02 16:45 UTC
Given a simple async fixture and test:

```python
@pytest.fixture()
async def my_client(aiohttp_client):
    return await aiohttp_client(make_app())

async def test_x(my_client):
    await my_client.get('/abc/')
```

Results in an exception: `AttributeError: 'coroutine' object has no attribute 'get'`

Downgrading to `pytest<3.7` fixed this.

**Comment by nicoddemus** [comment] 2018-08-02 16:50
Thanks for reporting, this is a duplicate of #89.

This will be fixed with `pytest 3.7.1`, due to be released today. 👍

**Closed by nicoddemus** 2018-08-02 16:50 UTC
