### ISSUE TITLE
0.23.3 breaking ImportError exception

### ISSUE THREAD

**Issue by mawildoer** [pytest-dev/pytest-asyncio#740] opened 2024-01-05 20:55 UTC
Hi folks!

I have run into what appears to be a new breaking chance on the 0.23.3 patch release.

```
INTERNALERROR> E   ImportError: cannot import name 'build' from '...' (.../__init__.py)
```

You can see the full builds here:
Passing (from before the release): https://gitlab.atopile.io/atopile/atopile/-/jobs/5893
Failing (after release): https://gitlab.atopile.io/atopile/atopile/-/jobs/6078

I pinned it to `pytest-asyncio` locally by updating and reverting across the two versions and I can replicate the failure.

Please let me know if there are any more details I can provide that would be useful!

Matt

**Comment by seifertm** [comment] 2024-01-07 16:12
Unfortunately, I cannot access the build logs. I get a 404 when I try.

This sounds pretty much like a duplicate of #729. I think it's a good idea that you subscribe to that issue. I just filed a PR that hopefully fixes it. I'm planning to create a pre-release of pytest-asyncio in the next few days for everyone to test and I'll announce it in #729.

**Closed by seifertm** 2024-01-07 16:12 UTC
