### ISSUE TITLE
async event emitter based on pytest-asyncio

### ISSUE THREAD

**Issue by wj-Mcat** [pytest-dev/pytest-asyncio#182] opened 2020-08-08 09:20 UTC
Recently I test my project based on async event emiiter, but all test get passed.

```python
import pytest
import asyncio
from pyee import AsyncIOEventEmitter

pytestmark = pytest.mark.asyncio


@pytest.fixture
async def emitter() -> AsyncIOEventEmitter:
    return AsyncIOEventEmitter(asyncio.get_event_loop())


async def test_event(emitter: AsyncIOEventEmitter):
    async def stream_event(data: str):
        assert data == '1'

    emitter.on('stream', stream_event)
    emitter.emit('stream', '2')

```

The test result is :

```text
============================= test session starts ==============================
platform darwin -- Python 3.7.7, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- /Users/someone/miniconda3/envs/wechaty_new/bin/python
cachedir: .pytest_cache
rootdir: /Users/someone/vscode/wechaty/python-wechaty-puppet-mock
plugins: Faker-4.1.1, asyncio-0.14.0
collecting ... collected 1 item

test_async_event.py::test_event 

============================== 1 passed in 0.09s ===============================

Process finished with exit code 0
PASSED                                   [100%]
```

Is there  another way to run the async event emitter test ?

**Comment by 1oglop1** [comment] 2020-08-19 10:04
@wj-Mcat this may help https://github.com/uhavin/slackers/blob/master/tests/slash_command.py

**Comment by Tinche** [comment] 2020-08-20 01:09
Mmm I don't know this library, but from a short test the problem is it swallows exceptions in the handlers. The design of the library makes it a little awkward to test.

Try this:
```
import pytest
import asyncio
from pyee import AsyncIOEventEmitter

pytestmark = pytest.mark.asyncio


@pytest.fixture
async def emitter(event_loop) -> AsyncIOEventEmitter:
    res = AsyncIOEventEmitter(event_loop)
    return res


async def test_event(emitter: AsyncIOEventEmitter):
    should_fail = False

    async def stream_event(data: str):
        nonlocal should_fail
        if data != "1":
            should_fail = True

    emitter.on("stream", stream_event)
    emitter.emit("stream", "2")

    await asyncio.sleep(0)

    assert not should_fail
```

**Comment by wj-Mcat** [comment] 2020-08-20 01:46
@Tinche Can you give me a python event-emitter package suggestion that support this test feature ? I need to test in mock .

**Comment by wj-Mcat** [comment] 2020-08-20 02:50
I finnaly find the test [example](https://github.com/jfhbrook/pyee/blob/master/tests/test_async.py#L29) from `pyee` repo.

**Comment by Tinche** [comment] 2020-08-20 22:18
Closing this then!

**Closed by Tinche** 2020-08-20 22:18 UTC
