### ISSUE TITLE
PytestDeprecationWarning: direct construction of Function has been deprecated

### ISSUE THREAD

**Issue by skewty** [pytest-dev/pytest-asyncio#147] opened 2020-03-21 03:51 UTC
pytest version 5.4.1

```
=============================== warnings summary ===============================
/home/scott/Projects/combox2/venv37/lib/python3.7/site-packages/pytest_asyncio/plugin.py:39
/home/scott/Projects/combox2/venv37/lib/python3.7/site-packages/pytest_asyncio/plugin.py:39
  /home/scott/Projects/combox2/venv37/lib/python3.7/site-packages/pytest_asyncio/plugin.py:39: PytestDeprecationWarning: direct construction of Function has been deprecated, please use Function.from_parent
    item = pytest.Function(name, parent=collector)

/home/scott/Projects/combox2/venv37/lib/python3.7/site-packages/pytest_asyncio/plugin.py:45
/home/scott/Projects/combox2/venv37/lib/python3.7/site-packages/pytest_asyncio/plugin.py:45
  /home/scott/Projects/combox2/venv37/lib/python3.7/site-packages/pytest_asyncio/plugin.py:45: PytestDeprecationWarning: direct construction of Function has been deprecated, please use Function.from_parent
    item = pytest.Function(name, parent=collector)  # To reload keywords.

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================== 1 passed, 4 warnings in 0.09s =========================
```

**Comment by simonfagerholm** [comment] 2020-03-23 06:14
Duplicate of #141

**Comment by simonfagerholm** [comment] 2020-03-31 11:45
Fixed in #142

**Closed** 2020-03-31 16:05 UTC
