### ISSUE TITLE
LICENSE file is not included in tarball on PyPI

### ISSUE THREAD

**Issue by FRidh** [pytest-dev/pytest-asyncio#92] opened 2018-08-25 05:51 UTC
```
writing requirements to pytest_asyncio.egg-info/requires.txt
writing top-level names to pytest_asyncio.egg-info/top_level.txt
reading manifest file 'pytest_asyncio.egg-info/SOURCES.txt'
writing manifest file 'pytest_asyncio.egg-info/SOURCES.txt'
Copying pytest_asyncio.egg-info to build/bdist.linux-x86_64/wheel/pytest_asyncio-0.9.0-py3.6.egg-info
running install_scripts
error: [Errno 2] No such file or directory: 'LICENSE'
```

**Comment by jraygauthier** [comment] 2018-11-12 18:04
Same issue here.

**Comment by blueyed** [comment] 2019-07-16 22:14
Closing as duplicate of https://github.com/pytest-dev/pytest-asyncio/issues/94 (although later).

**Closed by blueyed** 2019-07-16 22:14 UTC
