### ISSUE TITLE
If I parametrize a test with a single param == 'asyncio', pytest-asyncio tries to wrap the test into loop resulting in TypeError: An asyncio.Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by diefans** [pytest-dev/pytest-asyncio#100] opened 2018-10-17 08:48 UTC
```python
import pytest


@pytest.mark.parametrize('param', ['asyncio', 'foobar'])
def test_foobar(param):
    pass


@pytest.mark.parametrize('param, foo', [
    ('asyncio', 'foo'), ('foobar', 'bar')])
def test_foobar_working(param, foo):
    pass
```

```
tests/test_foobar.py::test_foobar[foobar] PASSED                                                                [ 25%]
tests/test_foobar.py::test_foobar[asyncio] FAILED                                                               [ 50%]
tests/test_foobar.py::test_foobar_working[foobar-bar] PASSED                                                    [ 75%]
tests/test_foobar.py::test_foobar_working[asyncio-foo] PASSED                                                   [100%]
```

IMHO I should be able to parametrize a test with the single value of `asyncio`.

**Comment by seifertm** [comment] 2022-01-16 09:02
@diefans Thanks for the report!

I couldn't reproduce your issue with pytest-asyncio-0.17.0, so I am closing this issue.

If you still experience problems, please reopen this issue or file a new one. We always appreciate bug reports :)

**Closed by seifertm** 2022-01-16 09:02 UTC
