### ISSUE TITLE
RuntimeError: Event loop is closed (pytest-asyncio 0.15.0+)

### ISSUE THREAD

**Issue by zakaprov** [pytest-dev/pytest-asyncio#211] opened 2021-05-05 16:53 UTC
## Environment
OS: Ubuntu 20.04.2 LTS
pytest version: 6.2.4
Python and `pytest-asyncio` version: see table below

## Issue description
I've noticed a suite of unit tests failing with a specific combination of Python and `pytest-asyncio` versions. Here's an example test run with multiple combinations, some of them failing: https://github.com/golemfactory/yapapi/actions/runs/813919338

Here's a table describing my observations (:green_circle: means the faulty test passed, :red_circle: means it failed):

Python version  /  `pytest-asyncio` version | 0.14.0 | 0.15.0 | 0.15.1
------------ | ------------- | ------------- | -------------
**3.6** | :green_circle: | :red_circle: | :red_circle: 
**3.7** | :green_circle: | :red_circle: | :red_circle: 
**3.8** | :green_circle: | :green_circle: | :green_circle: 
**3.9** | :green_circle: | :green_circle: | :green_circle: 

A here's the stack trace for the failures mentioned above:

```
    @pytest.hookimpl(hookwrapper=True)
    def pytest_fixture_setup(fixturedef, request):
        """Adjust the event loop policy when an event loop is produced."""
        if fixturedef.argname == "event_loop":
            outcome = yield
            loop = outcome.get_result()
            policy = asyncio.get_event_loop_policy()
            old_loop = policy.get_event_loop()
            if old_loop is not loop:
                old_loop.close()
>           policy.set_event_loop(loop)

../../../.virtualenvs/yapapi-3.6/lib/python3.6/site-packages/pytest_asyncio/plugin.py:97:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.6/asyncio/unix_events.py:1060: in set_event_loop
    self._watcher.attach_loop(loop)
/usr/lib/python3.6/asyncio/unix_events.py:815: in attach_loop
    self._do_waitpid_all()
/usr/lib/python3.6/asyncio/unix_events.py:885: in _do_waitpid_all
    self._do_waitpid(pid)
/usr/lib/python3.6/asyncio/unix_events.py:919: in _do_waitpid
    callback(pid, returncode, *args)
/usr/lib/python3.6/asyncio/unix_events.py:222: in _child_watcher_callback
    self.call_soon_threadsafe(transp._process_exited, returncode)
/usr/lib/python3.6/asyncio/base_events.py:641: in call_soon_threadsafe
    self._check_closed()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_UnixSelectorEventLoop running=False closed=True debug=False>

    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed

/usr/lib/python3.6/asyncio/base_events.py:381: RuntimeError
```

**Comment by Tinche** [comment] 2021-05-05 22:00
You don't need to test with 0.15.0, I'm aware the issue was present in that version.

Heh, on 3.6 and 3.7 *setting* the event loop fails? Dear lord.

**Comment by Tinche** [comment] 2021-05-05 22:02
Can you dig around why it fails and suggest a solution? That would speed things up.

**Comment by seifertm** [comment] 2021-05-21 07:04
@zakaprov Can you provide a (preferably minimal) reproducible example?
The commit referenced in your GitHub Actions run no longer exists.

**Comment by chrisk314** [comment] 2021-08-31 14:45
Hi, I'm also encountering this issue on Ubuntu 20.04. I have a suite of multiple tests. Each time I run any combination of the tests, the last test always fails with this error when cleaning up a session fixture which uses `loop.run_until_complete`. I am observing this problem with both python 3.7 and python 3.8, both on pytest 6.2.4 and pytest-asyncio 0.15.1.

**Comment by AIGeneratedUsername** [comment] 2021-09-02 06:32
**pytest-asyncio 0.15.1**
**Python 3.9**
I always get the following at the end of tests execution:


```
Unable to properly close all Redis instances: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<RedisConnection._read_data() running at /usr/local/lib/python3.8/site-packages/aioredis/connection.py:186> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4b6fa28b50>()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /usr/local/lib/python3.8/site-packages/aioredis/connection.py:168]>
```
----------

Another problem is that redefining `event_loop` with `scope="module"`: 
```python
# fixtures.py


@pytest.fixture(scope="module")
def event_loop() -> Generator[AbstractEventLoop, None, None]:
    loop = asyncio.get_event_loop()
    yield loop
    loop.close()

@pytest.fixture(scope="module")
async def api() -> AsyncGenerator[RestfulApi, None]:
    api = RestfulApi()
    await api.open_session()
    yield api
    await api.close_session()
```
leads to the error:
```
../../venv/lib/python3.9/site-packages/motor/metaprogramming.py:73: in method
    return framework.run_on_executor(loop,
../../venv/lib/python3.9/site-packages/motor/frameworks/asyncio/__init__.py:73: in run_on_executor
    return loop.run_in_executor(
/usr/lib/python3.9/asyncio/base_events.py:801: in run_in_executor
    self._check_closed()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=False closed=True debug=False>

    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed

/usr/lib/python3.9/asyncio/base_events.py:510: RuntimeError
```
when I run my tests.

**Comment by seifertm** [comment] 2021-09-14 16:40
This could be related to an ordering issue with the `event_loop` and the other fixtures.

@chrisk314 @AIGeneratedUsername Could either of you please run the problematic tests with `--setup-show` and post the output?

**Comment by seifertm** [comment] 2022-01-06 19:25
None of the participants in this issue have reacted to requests for more information. @Tinche I suggest closing this issue.

This issue was filed for pytest-asyncio 0.15. Please upgrade to v0.16 and check whether the experienced issues persist. If yes, feel free to reopen this issue, preferably providing a reproducible example.

**Comment by AIGeneratedUsername** [comment] 2022-01-06 20:26
+1 for closing this issue. I am not an author, so I can not do this.

Most likely my error was because of the Motor package (it is only my assumption).

**Closed** 2022-01-06 20:58 UTC
